services:
  laravel:
    image: php:8.4-cli
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - '8088:8000'
    volumes:
      - '.:/app'
    working_dir: /app
    networks:
      - sail

  fastapi_nlp:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - '8002:8000'
    volumes:
      - '../backend:/app'
    networks:
      - sail

networks:
  sail:
    driver: bridge
